### PR TITLE
Code Refactor Part 1 - Removal of Bencoding

### PR DESCRIPTION
**Pull request by jaitaiwan**
### Purpose
This PR introduces the following:
 - The complete removal of Bencoding.
 - Reliance on the external library CentricWebEstate\Bencode
 - Removal of PHP 5.4 as a supported PHP Version
 - Use of Composer's autoloader rather than our own implemention

### Rational
As per #44 this is to reduce the size of the overall PHPTracker project as well as increase the separation of concerns in the project.

CentricWebEstate\Bencode (in Bitbucket via composer) was chosen as the replacement for the existing Bencoding implementation as it is the fastest and most lightweight implementation I could find (single file include). The stats I ran showed that the difference between develop and the addition of this feature is slightly faster and slightly more (0.15mb) memory usage. This is likely due to the changes added to the PHPUnit.xml file so that we no longer rely on PHPTracker's autoloading but rather the autoloading build into composer.

Reliance on PHP 5.4 was removed as CentricWebEstate\Bencode required some PHP 5.5+ specific syntax as well as the fact that PHP 5.4 is 2 months from completely being unsupported.

So all in all a faster more separated set of changes.

@tcz Love it if you could take a quick look and let me know if you're happy for the merge. I'll merge in 7 days if there are no objections.

### CODE REVIEW

**Comment by jaitaiwan** [comment]
Not sure why scrutinizer has failed... Works with travis-ci.

**Comment by jaitaiwan** [comment]
@tcz can I get access to scrutinizer.

**Comment by tcz** [comment]
looks good :+1: 
access to Scrutinizer granted

**Comment by jaitaiwan** [comment]
Awesome thanks.

It occurred to me that where I'm going with a lot of my code changes and
what PHPTracker aims to be are two different things. As a result I'm
forking PHPTracker with my own fork LibtorrentPHP. In the spirit of OSS
I'll definitely still continue to help admin PHPTracker and will make sure
to port as many features etc across and still continue in the development
of PHPTracker.

So really the only difference will be that you'll receive patches from time
to time from my downstream fork as well as any help I would normally give
with PHPTracker just like this PR.

**Pull request closed without merging**
